services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    expose:
      - "8000"
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - SECRET_KEY=your-secret-key-here-change-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    volumes:
      - backend_data:/app
    command: >
      sh -c "
        python seed_data.py &&
        python main.py
      "
    restart: unless-stopped

  frontend:
    build: ./frontend
    expose:
      - "3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost
    depends_on:
      - backend
    restart: unless-stopped
    command: npm run dev

volumes:
  backend_data:
